### ISSUE TITLE
tests do not pass ?

### ISSUE THREAD

**Issue by fchapoton** [apaffenholz/pypolydb#2]
Running pytest, I got:
```
FAILED tests/test_polydb_collection.py::test_find_one - AssertionError: assert 'F.3D.0008' == 'F.3D.0002'
FAILED tests/test_polydb_collection.py::test_answer - AssertionError: assert 'F.3D.0008' == 'F.3D.0002'
```

**Comment by apaffenholz** [comment]
my bad. I guess I added the skip=3 to have this parameter tested,  but did not push the change in the expected outcome. F.3D.0008 is the correct answer. Fixed. 

Thanks very much for the pull request! Just merged. 
The module is still pretty basic and limited. If it is useful for something, I am happy to add more methods.
